import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.strategyBuilder": "Strategy Builder",
    "nav.simulations": "Simulations",
    "nav.compare": "Compare",
    "nav.portfolio": "Portfolio",
    "nav.marketData": "Market Data",
    "nav.settings": "Settings",
    "nav.mainMenu": "Main Menu",
    
    // Header
    "header.search": "Search stocks, strategies...",
    "header.notifications": "Notifications",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Monitor your trading strategies and portfolio performance",
    "dashboard.newStrategy": "New Strategy",
    "dashboard.totalPortfolioValue": "Total Portfolio Value",
    "dashboard.activeStrategies": "Active Strategies",
    "dashboard.bestStrategy": "Best Strategy",
    "dashboard.simulationsRun": "Simulations Run",
    "dashboard.recentSimulations": "Recent Simulations",
    "dashboard.viewAll": "View All",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.createNewStrategy": "Create New Strategy",
    "dashboard.runBacktest": "Run Backtest",
    "dashboard.compareStrategies": "Compare Strategies",
    "dashboard.popularTemplates": "Popular Templates",
    "dashboard.uses": "uses",
    "dashboard.ytd": "YTD",
    "dashboard.thisWeek": "this week",
    "dashboard.thisMonth": "this month",
    "dashboard.noSimulations": "No simulations yet",
    
    // Market
    "market.tasiMarket": "TASI Market",
    "market.closed": "Closed",
    "market.open": "Open",
    "market.topGainers": "Top Gainers",
    "market.topLosers": "Top Losers",
    "market.mostActive": "Most Active",
    "market.title": "Market Data",
    "market.subtitle": "Real-time Saudi stock market data and watchlist",
    "market.search": "Search stocks...",
    "market.all": "All",
    "market.watchlist": "Watchlist",
    "market.stock": "Stock",
    "market.price": "Price",
    "market.change": "Change",
    "market.volume": "Volume",
    "market.high": "High",
    "market.low": "Low",
    "market.marketCap": "Market Cap",
    
    // Strategy Builder
    "strategy.title": "Strategy Builder",
    "strategy.subtitle": "Design your trading strategy using mathematical equations",
    "strategy.strategyName": "Strategy Name",
    "strategy.enterName": "Enter strategy name",
    "strategy.selectStock": "Select Stock",
    "strategy.selectStockDesc": "Choose a stock to test your strategy",
    "strategy.dateRange": "Date Range",
    "strategy.startDate": "Start Date",
    "strategy.endDate": "End Date",
    "strategy.tradingEquation": "Trading Equation",
    "strategy.entryCondition": "Entry Condition (BUY)",
    "strategy.exitCondition": "Exit Condition (SELL)",
    "strategy.indicators": "Indicators",
    "strategy.operators": "Operators",
    "strategy.templates": "Templates",
    "strategy.saveStrategy": "Save Strategy",
    "strategy.runSimulation": "Run Simulation",
    "strategy.strategyInfo": "Strategy Information",
    "strategy.template": "Template",
    "strategy.loadTemplate": "Load from template...",
    "strategy.description": "Description",
    "strategy.descriptionPlaceholder": "Describe your strategy logic and rationale...",
    "strategy.entrySignal": "Entry Signal (Buy)",
    "strategy.exitSignal": "Exit Signal (Sell)",
    "strategy.validate": "Validate",
    "strategy.validating": "Validating...",
    "strategy.updateStrategy": "Update Strategy",
    "strategy.runBacktest": "Run Backtest",
    "strategy.aiAssistant": "AI Assistant",
    "strategy.reference": "Reference",
    "strategy.yourStrategies": "Your Strategies",
    "strategy.new": "New",
    "strategy.noStrategies": "No saved strategies yet",
    "strategy.createFirst": "Create your first strategy above",
    "strategy.deleteStrategy": "Delete Strategy",
    "strategy.deleteConfirm": "Are you sure you want to delete this strategy? This action cannot be undone.",
    "strategy.valid": "Valid",
    "strategy.invalid": "Invalid",
    "strategy.validMessage": "Strategy equations are valid and ready for backtesting.",
    "strategy.invalidMessage": "Please provide both entry and exit logic.",
    
    // Simulations
    "simulations.title": "Simulations",
    "simulations.subtitle": "Run backtests and analyze your strategy performance",
    "simulations.runNew": "Run New Simulation",
    "simulations.allSimulations": "All Simulations",
    "simulations.running": "Running",
    "simulations.completed": "Completed",
    "simulations.failed": "Failed",
    "simulations.totalReturn": "Total Return",
    "simulations.sharpeRatio": "Sharpe Ratio",
    "simulations.maxDrawdown": "Max Drawdown",
    "simulations.trades": "Trades",
    "simulations.configuration": "Configuration",
    "simulations.strategy": "Strategy",
    "simulations.selectStrategy": "Select a strategy",
    "simulations.asset": "Asset",
    "simulations.initialCapital": "Initial Capital (SAR)",
    "simulations.execution": "Execution",
    "simulations.commission": "Commission (%)",
    "simulations.slippage": "Slippage (bps)",
    "simulations.maxPosition": "Max Position (%)",
    "simulations.riskManagement": "Risk Management",
    "simulations.stopLoss": "Stop Loss (%)",
    "simulations.takeProfit": "Take Profit (%)",
    "simulations.trailingStop": "Trailing Stop (%)",
    "simulations.disabled": "Disabled",
    "simulations.exitIfLoss": "Exit if loss exceeds",
    "simulations.exitIfProfit": "Exit if profit exceeds",
    "simulations.trailBelow": "Trail below peak price",
    "simulations.runSimulation": "Run Simulation",
    "simulations.history": "History",
    "simulations.winRate": "Win Rate",
    "simulations.cagr": "CAGR",
    "simulations.totalTrades": "Total Trades",
    "simulations.winningTrades": "Winning Trades",
    "simulations.losingTrades": "Losing Trades",
    "simulations.stopLossExits": "Stop-Loss Exits",
    "simulations.takeProfitExits": "Take-Profit Exits",
    "simulations.trailingStopExits": "Trailing Stop Exits",
    "simulations.period": "Period",
    "simulations.days": "days",
    "simulations.equityCurve": "Equity Curve",
    "simulations.drawdown": "Drawdown",
    "simulations.monthlyReturns": "Monthly Returns",
    "simulations.tradeHistory": "Trade History",
    "simulations.date": "Date",
    "simulations.type": "Type",
    "simulations.exitReason": "Exit Reason",
    "simulations.quantity": "Quantity",
    "simulations.value": "Value",
    "simulations.pnl": "P&L",
    "simulations.noTradeData": "No trade data available",
    "simulations.noResults": "Select or run a simulation to see results",
    "simulations.noSimulations": "No simulations yet",
    "simulations.signal": "Signal",
    "simulations.entry": "Entry",
    
    // Compare
    "compare.title": "Compare Strategies",
    "compare.subtitle": "Compare performance across multiple strategies",
    "compare.selectStrategies": "Select Strategies to Compare",
    "compare.performanceMetrics": "Performance Metrics",
    "compare.equityCurve": "Equity Curve",
    "compare.drawdownChart": "Drawdown Chart",
    "compare.selectSimulations": "Select Simulations",
    "compare.selectToCompare": "Select simulations to compare",
    "compare.clearSelection": "Clear Selection",
    "compare.noSimulations": "No completed simulations available",
    "compare.runSimulations": "Run simulations first to compare them here",
    "compare.goToSimulations": "Go to Simulations",
    "compare.metrics": "Metrics",
    "compare.simulation": "Simulation",
    "compare.ticker": "Ticker",
    "compare.selectMultiple": "Select at least 2 simulations to compare",
    
    // Portfolio
    "portfolio.title": "Portfolio",
    "portfolio.subtitle": "Manage your paper trading portfolio",
    "portfolio.holdings": "Holdings",
    "portfolio.allocation": "Allocation",
    "portfolio.transactions": "Transactions",
    "portfolio.currentValue": "Current Value",
    "portfolio.totalGainLoss": "Total Gain/Loss",
    "portfolio.cash": "Cash",
    "portfolio.invested": "Invested",
    "portfolio.addTrade": "Add Trade",
    "portfolio.noHoldings": "No holdings yet",
    "portfolio.startTrading": "Start trading to build your portfolio",
    "portfolio.noTransactions": "No transactions yet",
    "portfolio.stock": "Stock",
    "portfolio.shares": "Shares",
    "portfolio.avgPrice": "Avg Price",
    "portfolio.price": "Price",
    "portfolio.date": "Date",
    "portfolio.type": "Type",
    "portfolio.quantity": "Quantity",
    "portfolio.value": "Value",
    "portfolio.buy": "Buy",
    "portfolio.sell": "Sell",
    
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account and trading preferences",
    "settings.profile": "Profile",
    "settings.riskManagement": "Risk Management",
    "settings.execution": "Execution",
    "settings.accountInfo": "Account Information",
    "settings.fullName": "Full Name",
    "settings.email": "Email",
    "settings.timezone": "Timezone",
    "settings.saveChanges": "Save Changes",
    "settings.defaultRiskProfile": "Default Risk Profile",
    "settings.reset": "Reset",
    "settings.maxPositionSize": "Max Position Size",
    "settings.defaultStopLoss": "Default Stop Loss",
    "settings.defaultTakeProfit": "Default Take Profit",
    "settings.saveRiskProfile": "Save Risk Profile",
    "settings.defaultExecutionSettings": "Default Execution Settings",
    "settings.defaultCommission": "Default Commission",
    "settings.defaultSlippage": "Default Slippage",
    "settings.initialCapital": "Initial Capital",
    "settings.saveSettings": "Save Settings",
    "settings.resetToDefault": "Reset to defaults",
    
    // Charts
    "charts.equityCurve": "Equity Curve",
    "charts.monthlyReturns": "Monthly Returns",
    "charts.drawdown": "Drawdown",
    "charts.portfolioValue": "Portfolio Value",
    "charts.benchmark": "Benchmark",
    "charts.strategy": "Strategy",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.reset": "Reset",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.actions": "Actions",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    "common.or": "or",
    "common.and": "and",
    
    // Branding
    "brand.name": "TASI",
    "brand.tagline": "Simulator",
    
    // Auth
    "auth.title": "Murabaha Lab",
    "auth.subtitle": "Trading strategy backtesting platform",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.login": "Login",
    "auth.logout": "Logout",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.fullName": "Full Name",
    "auth.forgotPassword": "Forgot Password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.signInError": "Sign in failed",
    "auth.signUpError": "Sign up failed",
    "auth.signUpSuccess": "Account created!",
    "auth.signUpSuccessDesc": "You can now sign in with your credentials",
    "auth.invalidCredentials": "Invalid email or password",
    "auth.userExists": "An account with this email already exists",
  },
  ar: {
    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.strategyBuilder": "منشئ الاستراتيجيات",
    "nav.simulations": "المحاكاة",
    "nav.compare": "المقارنة",
    "nav.portfolio": "المحفظة",
    "nav.marketData": "بيانات السوق",
    "nav.settings": "الإعدادات",
    "nav.mainMenu": "القائمة الرئيسية",
    
    // Header
    "header.search": "بحث عن أسهم، استراتيجيات...",
    "header.notifications": "الإشعارات",
    
    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.subtitle": "راقب استراتيجيات التداول وأداء محفظتك",
    "dashboard.newStrategy": "استراتيجية جديدة",
    "dashboard.totalPortfolioValue": "إجمالي قيمة المحفظة",
    "dashboard.activeStrategies": "الاستراتيجيات النشطة",
    "dashboard.bestStrategy": "أفضل استراتيجية",
    "dashboard.simulationsRun": "المحاكاة المنفذة",
    "dashboard.recentSimulations": "المحاكاة الأخيرة",
    "dashboard.viewAll": "عرض الكل",
    "dashboard.quickActions": "إجراءات سريعة",
    "dashboard.createNewStrategy": "إنشاء استراتيجية جديدة",
    "dashboard.runBacktest": "تشغيل اختبار رجعي",
    "dashboard.compareStrategies": "مقارنة الاستراتيجيات",
    "dashboard.popularTemplates": "القوالب الشائعة",
    "dashboard.uses": "استخدام",
    "dashboard.ytd": "منذ بداية العام",
    "dashboard.thisWeek": "هذا الأسبوع",
    "dashboard.thisMonth": "هذا الشهر",
    "dashboard.noSimulations": "لا توجد محاكاة بعد",
    
    // Market
    "market.tasiMarket": "سوق تاسي",
    "market.closed": "مغلق",
    "market.open": "مفتوح",
    "market.topGainers": "الأكثر ارتفاعاً",
    "market.topLosers": "الأكثر انخفاضاً",
    "market.mostActive": "الأكثر نشاطاً",
    "market.title": "بيانات السوق",
    "market.subtitle": "بيانات سوق الأسهم السعودي ومحفظة المراقبة",
    "market.search": "البحث عن أسهم...",
    "market.all": "الكل",
    "market.watchlist": "المراقبة",
    "market.stock": "السهم",
    "market.price": "السعر",
    "market.change": "التغيير",
    "market.volume": "الحجم",
    "market.high": "الأعلى",
    "market.low": "الأدنى",
    "market.marketCap": "القيمة السوقية",
    
    // Strategy Builder
    "strategy.title": "منشئ الاستراتيجيات",
    "strategy.subtitle": "صمم استراتيجية التداول باستخدام المعادلات الرياضية",
    "strategy.strategyName": "اسم الاستراتيجية",
    "strategy.enterName": "أدخل اسم الاستراتيجية",
    "strategy.selectStock": "اختر السهم",
    "strategy.selectStockDesc": "اختر سهماً لاختبار استراتيجيتك",
    "strategy.dateRange": "النطاق الزمني",
    "strategy.startDate": "تاريخ البداية",
    "strategy.endDate": "تاريخ النهاية",
    "strategy.tradingEquation": "معادلة التداول",
    "strategy.entryCondition": "شرط الدخول (شراء)",
    "strategy.exitCondition": "شرط الخروج (بيع)",
    "strategy.indicators": "المؤشرات",
    "strategy.operators": "العوامل",
    "strategy.templates": "القوالب",
    "strategy.saveStrategy": "حفظ الاستراتيجية",
    "strategy.runSimulation": "تشغيل المحاكاة",
    "strategy.strategyInfo": "معلومات الاستراتيجية",
    "strategy.template": "القالب",
    "strategy.loadTemplate": "تحميل من قالب...",
    "strategy.description": "الوصف",
    "strategy.descriptionPlaceholder": "صف منطق استراتيجيتك...",
    "strategy.entrySignal": "إشارة الدخول (شراء)",
    "strategy.exitSignal": "إشارة الخروج (بيع)",
    "strategy.validate": "التحقق",
    "strategy.validating": "جاري التحقق...",
    "strategy.updateStrategy": "تحديث الاستراتيجية",
    "strategy.runBacktest": "تشغيل الاختبار الرجعي",
    "strategy.aiAssistant": "مساعد الذكاء الاصطناعي",
    "strategy.reference": "المرجع",
    "strategy.yourStrategies": "استراتيجياتك",
    "strategy.new": "جديد",
    "strategy.noStrategies": "لا توجد استراتيجيات محفوظة",
    "strategy.createFirst": "أنشئ استراتيجيتك الأولى",
    "strategy.deleteStrategy": "حذف الاستراتيجية",
    "strategy.deleteConfirm": "هل أنت متأكد من حذف هذه الاستراتيجية؟ لا يمكن التراجع عن هذا الإجراء.",
    "strategy.valid": "صالح",
    "strategy.invalid": "غير صالح",
    "strategy.validMessage": "معادلات الاستراتيجية صالحة وجاهزة للاختبار.",
    "strategy.invalidMessage": "يرجى تقديم كل من منطق الدخول والخروج.",
    
    // Simulations
    "simulations.title": "المحاكاة",
    "simulations.subtitle": "شغّل اختبارات رجعية وحلل أداء استراتيجيتك",
    "simulations.runNew": "تشغيل محاكاة جديدة",
    "simulations.allSimulations": "جميع المحاكاة",
    "simulations.running": "قيد التنفيذ",
    "simulations.completed": "مكتملة",
    "simulations.failed": "فشلت",
    "simulations.totalReturn": "العائد الإجمالي",
    "simulations.sharpeRatio": "نسبة شارب",
    "simulations.maxDrawdown": "أقصى تراجع",
    "simulations.trades": "الصفقات",
    "simulations.configuration": "الإعدادات",
    "simulations.strategy": "الاستراتيجية",
    "simulations.selectStrategy": "اختر استراتيجية",
    "simulations.asset": "الأصل",
    "simulations.initialCapital": "رأس المال الابتدائي (ريال)",
    "simulations.execution": "التنفيذ",
    "simulations.commission": "العمولة (%)",
    "simulations.slippage": "الانزلاق (نقطة أساس)",
    "simulations.maxPosition": "الحد الأقصى للمركز (%)",
    "simulations.riskManagement": "إدارة المخاطر",
    "simulations.stopLoss": "وقف الخسارة (%)",
    "simulations.takeProfit": "جني الأرباح (%)",
    "simulations.trailingStop": "وقف الخسارة المتحرك (%)",
    "simulations.disabled": "معطل",
    "simulations.exitIfLoss": "خروج إذا تجاوزت الخسارة",
    "simulations.exitIfProfit": "خروج إذا تجاوز الربح",
    "simulations.trailBelow": "تتبع أسفل السعر الأعلى",
    "simulations.runSimulation": "تشغيل المحاكاة",
    "simulations.history": "السجل",
    "simulations.winRate": "نسبة الفوز",
    "simulations.cagr": "معدل النمو السنوي المركب",
    "simulations.totalTrades": "إجمالي الصفقات",
    "simulations.winningTrades": "الصفقات الرابحة",
    "simulations.losingTrades": "الصفقات الخاسرة",
    "simulations.stopLossExits": "خروج بوقف الخسارة",
    "simulations.takeProfitExits": "خروج بجني الأرباح",
    "simulations.trailingStopExits": "خروج بالوقف المتحرك",
    "simulations.period": "الفترة",
    "simulations.days": "يوم",
    "simulations.equityCurve": "منحنى رأس المال",
    "simulations.drawdown": "التراجع",
    "simulations.monthlyReturns": "العوائد الشهرية",
    "simulations.tradeHistory": "سجل الصفقات",
    "simulations.date": "التاريخ",
    "simulations.type": "النوع",
    "simulations.exitReason": "سبب الخروج",
    "simulations.quantity": "الكمية",
    "simulations.value": "القيمة",
    "simulations.pnl": "الربح/الخسارة",
    "simulations.noTradeData": "لا توجد بيانات صفقات",
    "simulations.noResults": "اختر أو شغّل محاكاة لرؤية النتائج",
    "simulations.noSimulations": "لا توجد محاكاة بعد",
    "simulations.signal": "إشارة",
    "simulations.entry": "دخول",
    
    // Compare
    "compare.title": "مقارنة الاستراتيجيات",
    "compare.subtitle": "قارن الأداء بين عدة استراتيجيات",
    "compare.selectStrategies": "اختر استراتيجيات للمقارنة",
    "compare.performanceMetrics": "مقاييس الأداء",
    "compare.equityCurve": "منحنى رأس المال",
    "compare.drawdownChart": "مخطط التراجع",
    "compare.selectSimulations": "اختر المحاكاة",
    "compare.selectToCompare": "اختر المحاكاة للمقارنة",
    "compare.clearSelection": "مسح الاختيار",
    "compare.noSimulations": "لا توجد محاكاة مكتملة",
    "compare.runSimulations": "شغّل محاكاة أولاً للمقارنة هنا",
    "compare.goToSimulations": "الذهاب إلى المحاكاة",
    "compare.metrics": "المقاييس",
    "compare.simulation": "المحاكاة",
    "compare.ticker": "الرمز",
    "compare.selectMultiple": "اختر محاكاتين على الأقل للمقارنة",
    
    // Portfolio
    "portfolio.title": "المحفظة",
    "portfolio.subtitle": "أدر محفظة التداول الورقي",
    "portfolio.holdings": "الممتلكات",
    "portfolio.allocation": "التوزيع",
    "portfolio.transactions": "المعاملات",
    "portfolio.currentValue": "القيمة الحالية",
    "portfolio.totalGainLoss": "إجمالي الربح/الخسارة",
    "portfolio.cash": "نقد",
    "portfolio.invested": "مستثمر",
    "portfolio.addTrade": "إضافة صفقة",
    "portfolio.noHoldings": "لا توجد ممتلكات بعد",
    "portfolio.startTrading": "ابدأ التداول لبناء محفظتك",
    "portfolio.noTransactions": "لا توجد معاملات بعد",
    "portfolio.stock": "السهم",
    "portfolio.shares": "الأسهم",
    "portfolio.avgPrice": "متوسط السعر",
    "portfolio.price": "السعر",
    "portfolio.date": "التاريخ",
    "portfolio.type": "النوع",
    "portfolio.quantity": "الكمية",
    "portfolio.value": "القيمة",
    "portfolio.buy": "شراء",
    "portfolio.sell": "بيع",
    
    // Settings
    "settings.title": "الإعدادات",
    "settings.subtitle": "إدارة حسابك وتفضيلات التداول",
    "settings.profile": "الملف الشخصي",
    "settings.riskManagement": "إدارة المخاطر",
    "settings.execution": "التنفيذ",
    "settings.accountInfo": "معلومات الحساب",
    "settings.fullName": "الاسم الكامل",
    "settings.email": "البريد الإلكتروني",
    "settings.timezone": "المنطقة الزمنية",
    "settings.saveChanges": "حفظ التغييرات",
    "settings.defaultRiskProfile": "ملف المخاطر الافتراضي",
    "settings.reset": "إعادة تعيين",
    "settings.maxPositionSize": "الحد الأقصى لحجم المركز",
    "settings.defaultStopLoss": "وقف الخسارة الافتراضي",
    "settings.defaultTakeProfit": "جني الأرباح الافتراضي",
    "settings.saveRiskProfile": "حفظ ملف المخاطر",
    "settings.defaultExecutionSettings": "إعدادات التنفيذ الافتراضية",
    "settings.defaultCommission": "العمولة الافتراضية",
    "settings.defaultSlippage": "الانزلاق الافتراضي",
    "settings.initialCapital": "رأس المال الابتدائي",
    "settings.saveSettings": "حفظ الإعدادات",
    "settings.resetToDefault": "إعادة تعيين للافتراضي",
    
    // Charts
    "charts.equityCurve": "منحنى رأس المال",
    "charts.monthlyReturns": "العوائد الشهرية",
    "charts.drawdown": "التراجع",
    "charts.portfolioValue": "قيمة المحفظة",
    "charts.benchmark": "المؤشر المرجعي",
    "charts.strategy": "الاستراتيجية",
    
    // Common
    "common.loading": "جاري التحميل...",
    "common.error": "خطأ",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.view": "عرض",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.submit": "إرسال",
    "common.reset": "إعادة تعيين",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.sort": "ترتيب",
    "common.actions": "الإجراءات",
    "common.close": "إغلاق",
    "common.confirm": "تأكيد",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.or": "أو",
    "common.and": "و",
    
    // Branding
    "brand.name": "تاسي",
    "brand.tagline": "المحاكي",
    
    // Auth
    "auth.title": "معمل المرابحة",
    "auth.subtitle": "منصة اختبار استراتيجيات التداول",
    "auth.signIn": "تسجيل الدخول",
    "auth.signUp": "إنشاء حساب",
    "auth.login": "تسجيل الدخول",
    "auth.logout": "تسجيل الخروج",
    "auth.signup": "إنشاء حساب",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.fullName": "الاسم الكامل",
    "auth.forgotPassword": "نسيت كلمة المرور؟",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.hasAccount": "لديك حساب بالفعل؟",
    "auth.signInError": "فشل تسجيل الدخول",
    "auth.signUpError": "فشل إنشاء الحساب",
    "auth.signUpSuccess": "تم إنشاء الحساب!",
    "auth.signUpSuccessDesc": "يمكنك الآن تسجيل الدخول باستخدام بياناتك",
    "auth.invalidCredentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    "auth.userExists": "يوجد حساب بهذا البريد الإلكتروني بالفعل",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "ar";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
